refactor: rename content information fileds
content-ethereum/Simple-Content-NFT pull request #1
Opened 2022-11-16 09:08 UTC by cblk

2022-11-16 09:24 UTC, YErikOhtake requested changes
I have reviewed. Please correct the source.

2022-11-16 09:24 UTC, YErikOhtake commented on simpleContentNft
> +        string[] _Documents; // contract documents: text or URI
Property names must begin with a lowercase letter.

2022-11-16 09:24 UTC, YErikOhtake commented on simpleContentNft
> +        uint256[] _Ratio; // copyright fee ratio of NFT
Property names must begin with a lowercase letter.

2022-11-16 09:24 UTC, YErikOhtake commented on simpleContentNft
> +        string[] memory pi = _contents[tokenId]._info;
The variable name "pi" does not indicate the entity.
The variable name should be "info".
"cds", "crfr", and "asm" are also the same review comments.

2022-11-21 08:59 UTC, cblk commented on simpleContentNft
> +        string[] _Documents; // contract documents: text or URI
ok

2022-11-21 08:59 UTC, cblk commented on simpleContentNft
> +        uint256[] _Ratio; // copyright fee ratio of NFT
ok

2022-11-21 09:06 UTC, YErikOhtake approved these changes

2022-12-22 05:28 UTC, KojiMachi commented
Thanks for your cooperation.

2022-12-22 05:29 UTC, merged